### PR TITLE
[Merged by Bors] - Update dyno and redis plans for prod

### PR DESCRIPTION
**Pull request by sjohnson31**

### CODE REVIEW

**Comment by sjohnson31** [comment]
bors merge

**Review by sburba — APPROVED** [review]

**Comment by sjohnson31** [comment]
bors merge

**Comment by sjohnson31** [comment]
bors merge

**Comment by sjohnson31** [comment]
bors merge

**Comment by sjohnson31** [comment]
bors merge

**Comment by sjohnson31** [comment]
bors merge

**Pull request closed without merging**
